/*
openobserve

OpenObserve API documents [https://openobserve.ai/docs/](https://openobserve.ai/docs/)

API version: 0.14.5
Contact: hello@zinclabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HealthzResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthzResponse{}

// HealthzResponse struct for HealthzResponse
type HealthzResponse struct {
	Status string `json:"status"`
}

type _HealthzResponse HealthzResponse

// NewHealthzResponse instantiates a new HealthzResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthzResponse(status string) *HealthzResponse {
	this := HealthzResponse{}
	this.Status = status
	return &this
}

// NewHealthzResponseWithDefaults instantiates a new HealthzResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthzResponseWithDefaults() *HealthzResponse {
	this := HealthzResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *HealthzResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HealthzResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HealthzResponse) SetStatus(v string) {
	o.Status = v
}

func (o HealthzResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthzResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *HealthzResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthzResponse := _HealthzResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthzResponse)

	if err != nil {
		return err
	}

	*o = HealthzResponse(varHealthzResponse)

	return err
}

type NullableHealthzResponse struct {
	value *HealthzResponse
	isSet bool
}

func (v NullableHealthzResponse) Get() *HealthzResponse {
	return v.value
}

func (v *NullableHealthzResponse) Set(val *HealthzResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthzResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthzResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthzResponse(val *HealthzResponse) *NullableHealthzResponse {
	return &NullableHealthzResponse{value: val, isSet: true}
}

func (v NullableHealthzResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthzResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


