/*
openobserve

OpenObserve API documents [https://openobserve.ai/docs/](https://openobserve.ai/docs/)

API version: 0.14.5
Contact: hello@zinclabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StreamDeleteFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamDeleteFields{}

// StreamDeleteFields struct for StreamDeleteFields
type StreamDeleteFields struct {
	Fields []string `json:"fields"`
}

type _StreamDeleteFields StreamDeleteFields

// NewStreamDeleteFields instantiates a new StreamDeleteFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamDeleteFields(fields []string) *StreamDeleteFields {
	this := StreamDeleteFields{}
	this.Fields = fields
	return &this
}

// NewStreamDeleteFieldsWithDefaults instantiates a new StreamDeleteFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamDeleteFieldsWithDefaults() *StreamDeleteFields {
	this := StreamDeleteFields{}
	return &this
}

// GetFields returns the Fields field value
func (o *StreamDeleteFields) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *StreamDeleteFields) GetFieldsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *StreamDeleteFields) SetFields(v []string) {
	o.Fields = v
}

func (o StreamDeleteFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamDeleteFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

func (o *StreamDeleteFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamDeleteFields := _StreamDeleteFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStreamDeleteFields)

	if err != nil {
		return err
	}

	*o = StreamDeleteFields(varStreamDeleteFields)

	return err
}

type NullableStreamDeleteFields struct {
	value *StreamDeleteFields
	isSet bool
}

func (v NullableStreamDeleteFields) Get() *StreamDeleteFields {
	return v.value
}

func (v *NullableStreamDeleteFields) Set(val *StreamDeleteFields) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamDeleteFields) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamDeleteFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamDeleteFields(val *StreamDeleteFields) *NullableStreamDeleteFields {
	return &NullableStreamDeleteFields{value: val, isSet: true}
}

func (v NullableStreamDeleteFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamDeleteFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


