/*
openobserve

OpenObserve API documents [https://openobserve.ai/docs/](https://openobserve.ai/docs/)

API version: 0.14.5
Contact: hello@zinclabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StreamProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamProperty{}

// StreamProperty struct for StreamProperty
type StreamProperty struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type _StreamProperty StreamProperty

// NewStreamProperty instantiates a new StreamProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamProperty(name string, type_ string) *StreamProperty {
	this := StreamProperty{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewStreamPropertyWithDefaults instantiates a new StreamProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamPropertyWithDefaults() *StreamProperty {
	this := StreamProperty{}
	return &this
}

// GetName returns the Name field value
func (o *StreamProperty) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StreamProperty) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StreamProperty) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *StreamProperty) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StreamProperty) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StreamProperty) SetType(v string) {
	o.Type = v
}

func (o StreamProperty) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *StreamProperty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamProperty := _StreamProperty{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStreamProperty)

	if err != nil {
		return err
	}

	*o = StreamProperty(varStreamProperty)

	return err
}

type NullableStreamProperty struct {
	value *StreamProperty
	isSet bool
}

func (v NullableStreamProperty) Get() *StreamProperty {
	return v.value
}

func (v *NullableStreamProperty) Set(val *StreamProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamProperty(val *StreamProperty) *NullableStreamProperty {
	return &NullableStreamProperty{value: val, isSet: true}
}

func (v NullableStreamProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


