/*
openobserve

OpenObserve API documents [https://openobserve.ai/docs/](https://openobserve.ai/docs/)

API version: 0.14.5
Contact: hello@zinclabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PasscodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PasscodeResponse{}

// PasscodeResponse struct for PasscodeResponse
type PasscodeResponse struct {
	Data IngestionPasscode `json:"data"`
}

type _PasscodeResponse PasscodeResponse

// NewPasscodeResponse instantiates a new PasscodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPasscodeResponse(data IngestionPasscode) *PasscodeResponse {
	this := PasscodeResponse{}
	this.Data = data
	return &this
}

// NewPasscodeResponseWithDefaults instantiates a new PasscodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasscodeResponseWithDefaults() *PasscodeResponse {
	this := PasscodeResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PasscodeResponse) GetData() IngestionPasscode {
	if o == nil {
		var ret IngestionPasscode
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PasscodeResponse) GetDataOk() (*IngestionPasscode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PasscodeResponse) SetData(v IngestionPasscode) {
	o.Data = v
}

func (o PasscodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PasscodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PasscodeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPasscodeResponse := _PasscodeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPasscodeResponse)

	if err != nil {
		return err
	}

	*o = PasscodeResponse(varPasscodeResponse)

	return err
}

type NullablePasscodeResponse struct {
	value *PasscodeResponse
	isSet bool
}

func (v NullablePasscodeResponse) Get() *PasscodeResponse {
	return v.value
}

func (v *NullablePasscodeResponse) Set(val *PasscodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePasscodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePasscodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasscodeResponse(val *PasscodeResponse) *NullablePasscodeResponse {
	return &NullablePasscodeResponse{value: val, isSet: true}
}

func (v NullablePasscodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasscodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


