/*
openobserve

OpenObserve API documents [https://openobserve.ai/docs/](https://openobserve.ai/docs/)

API version: 0.14.5
Contact: hello@zinclabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ListDashboardsResponseBodyItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDashboardsResponseBodyItem{}

// ListDashboardsResponseBodyItem An item in the list returned by the `ListDashboards` endpoint.
type ListDashboardsResponseBodyItem struct {
	Created time.Time `json:"created"`
	DashboardId string `json:"dashboard_id"`
	Description string `json:"description"`
	FolderId string `json:"folder_id"`
	FolderName string `json:"folder_name"`
	Hash string `json:"hash"`
	Owner string `json:"owner"`
	Role string `json:"role"`
	Title string `json:"title"`
	UpdatedAt int64 `json:"updatedAt"`
	V1 NullableV1Dashboard `json:"v1,omitempty"`
	V2 NullableV2Dashboard `json:"v2,omitempty"`
	V3 NullableV3Dashboard `json:"v3,omitempty"`
	V4 NullableV4Dashboard `json:"v4,omitempty"`
	V5 NullableV5Dashboard `json:"v5,omitempty"`
	Version int32 `json:"version"`
}

type _ListDashboardsResponseBodyItem ListDashboardsResponseBodyItem

// NewListDashboardsResponseBodyItem instantiates a new ListDashboardsResponseBodyItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDashboardsResponseBodyItem(created time.Time, dashboardId string, description string, folderId string, folderName string, hash string, owner string, role string, title string, updatedAt int64, version int32) *ListDashboardsResponseBodyItem {
	this := ListDashboardsResponseBodyItem{}
	this.Created = created
	this.DashboardId = dashboardId
	this.Description = description
	this.FolderId = folderId
	this.FolderName = folderName
	this.Hash = hash
	this.Owner = owner
	this.Role = role
	this.Title = title
	this.UpdatedAt = updatedAt
	this.Version = version
	return &this
}

// NewListDashboardsResponseBodyItemWithDefaults instantiates a new ListDashboardsResponseBodyItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDashboardsResponseBodyItemWithDefaults() *ListDashboardsResponseBodyItem {
	this := ListDashboardsResponseBodyItem{}
	return &this
}

// GetCreated returns the Created field value
func (o *ListDashboardsResponseBodyItem) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ListDashboardsResponseBodyItem) SetCreated(v time.Time) {
	o.Created = v
}

// GetDashboardId returns the DashboardId field value
func (o *ListDashboardsResponseBodyItem) GetDashboardId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DashboardId
}

// GetDashboardIdOk returns a tuple with the DashboardId field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetDashboardIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DashboardId, true
}

// SetDashboardId sets field value
func (o *ListDashboardsResponseBodyItem) SetDashboardId(v string) {
	o.DashboardId = v
}

// GetDescription returns the Description field value
func (o *ListDashboardsResponseBodyItem) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ListDashboardsResponseBodyItem) SetDescription(v string) {
	o.Description = v
}

// GetFolderId returns the FolderId field value
func (o *ListDashboardsResponseBodyItem) GetFolderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FolderId
}

// GetFolderIdOk returns a tuple with the FolderId field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetFolderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FolderId, true
}

// SetFolderId sets field value
func (o *ListDashboardsResponseBodyItem) SetFolderId(v string) {
	o.FolderId = v
}

// GetFolderName returns the FolderName field value
func (o *ListDashboardsResponseBodyItem) GetFolderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetFolderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FolderName, true
}

// SetFolderName sets field value
func (o *ListDashboardsResponseBodyItem) SetFolderName(v string) {
	o.FolderName = v
}

// GetHash returns the Hash field value
func (o *ListDashboardsResponseBodyItem) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *ListDashboardsResponseBodyItem) SetHash(v string) {
	o.Hash = v
}

// GetOwner returns the Owner field value
func (o *ListDashboardsResponseBodyItem) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *ListDashboardsResponseBodyItem) SetOwner(v string) {
	o.Owner = v
}

// GetRole returns the Role field value
func (o *ListDashboardsResponseBodyItem) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ListDashboardsResponseBodyItem) SetRole(v string) {
	o.Role = v
}

// GetTitle returns the Title field value
func (o *ListDashboardsResponseBodyItem) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ListDashboardsResponseBodyItem) SetTitle(v string) {
	o.Title = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListDashboardsResponseBodyItem) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListDashboardsResponseBodyItem) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

// GetV1 returns the V1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListDashboardsResponseBodyItem) GetV1() V1Dashboard {
	if o == nil || IsNil(o.V1.Get()) {
		var ret V1Dashboard
		return ret
	}
	return *o.V1.Get()
}

// GetV1Ok returns a tuple with the V1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListDashboardsResponseBodyItem) GetV1Ok() (*V1Dashboard, bool) {
	if o == nil {
		return nil, false
	}
	return o.V1.Get(), o.V1.IsSet()
}

// HasV1 returns a boolean if a field has been set.
func (o *ListDashboardsResponseBodyItem) HasV1() bool {
	if o != nil && o.V1.IsSet() {
		return true
	}

	return false
}

// SetV1 gets a reference to the given NullableV1Dashboard and assigns it to the V1 field.
func (o *ListDashboardsResponseBodyItem) SetV1(v V1Dashboard) {
	o.V1.Set(&v)
}
// SetV1Nil sets the value for V1 to be an explicit nil
func (o *ListDashboardsResponseBodyItem) SetV1Nil() {
	o.V1.Set(nil)
}

// UnsetV1 ensures that no value is present for V1, not even an explicit nil
func (o *ListDashboardsResponseBodyItem) UnsetV1() {
	o.V1.Unset()
}

// GetV2 returns the V2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListDashboardsResponseBodyItem) GetV2() V2Dashboard {
	if o == nil || IsNil(o.V2.Get()) {
		var ret V2Dashboard
		return ret
	}
	return *o.V2.Get()
}

// GetV2Ok returns a tuple with the V2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListDashboardsResponseBodyItem) GetV2Ok() (*V2Dashboard, bool) {
	if o == nil {
		return nil, false
	}
	return o.V2.Get(), o.V2.IsSet()
}

// HasV2 returns a boolean if a field has been set.
func (o *ListDashboardsResponseBodyItem) HasV2() bool {
	if o != nil && o.V2.IsSet() {
		return true
	}

	return false
}

// SetV2 gets a reference to the given NullableV2Dashboard and assigns it to the V2 field.
func (o *ListDashboardsResponseBodyItem) SetV2(v V2Dashboard) {
	o.V2.Set(&v)
}
// SetV2Nil sets the value for V2 to be an explicit nil
func (o *ListDashboardsResponseBodyItem) SetV2Nil() {
	o.V2.Set(nil)
}

// UnsetV2 ensures that no value is present for V2, not even an explicit nil
func (o *ListDashboardsResponseBodyItem) UnsetV2() {
	o.V2.Unset()
}

// GetV3 returns the V3 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListDashboardsResponseBodyItem) GetV3() V3Dashboard {
	if o == nil || IsNil(o.V3.Get()) {
		var ret V3Dashboard
		return ret
	}
	return *o.V3.Get()
}

// GetV3Ok returns a tuple with the V3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListDashboardsResponseBodyItem) GetV3Ok() (*V3Dashboard, bool) {
	if o == nil {
		return nil, false
	}
	return o.V3.Get(), o.V3.IsSet()
}

// HasV3 returns a boolean if a field has been set.
func (o *ListDashboardsResponseBodyItem) HasV3() bool {
	if o != nil && o.V3.IsSet() {
		return true
	}

	return false
}

// SetV3 gets a reference to the given NullableV3Dashboard and assigns it to the V3 field.
func (o *ListDashboardsResponseBodyItem) SetV3(v V3Dashboard) {
	o.V3.Set(&v)
}
// SetV3Nil sets the value for V3 to be an explicit nil
func (o *ListDashboardsResponseBodyItem) SetV3Nil() {
	o.V3.Set(nil)
}

// UnsetV3 ensures that no value is present for V3, not even an explicit nil
func (o *ListDashboardsResponseBodyItem) UnsetV3() {
	o.V3.Unset()
}

// GetV4 returns the V4 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListDashboardsResponseBodyItem) GetV4() V4Dashboard {
	if o == nil || IsNil(o.V4.Get()) {
		var ret V4Dashboard
		return ret
	}
	return *o.V4.Get()
}

// GetV4Ok returns a tuple with the V4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListDashboardsResponseBodyItem) GetV4Ok() (*V4Dashboard, bool) {
	if o == nil {
		return nil, false
	}
	return o.V4.Get(), o.V4.IsSet()
}

// HasV4 returns a boolean if a field has been set.
func (o *ListDashboardsResponseBodyItem) HasV4() bool {
	if o != nil && o.V4.IsSet() {
		return true
	}

	return false
}

// SetV4 gets a reference to the given NullableV4Dashboard and assigns it to the V4 field.
func (o *ListDashboardsResponseBodyItem) SetV4(v V4Dashboard) {
	o.V4.Set(&v)
}
// SetV4Nil sets the value for V4 to be an explicit nil
func (o *ListDashboardsResponseBodyItem) SetV4Nil() {
	o.V4.Set(nil)
}

// UnsetV4 ensures that no value is present for V4, not even an explicit nil
func (o *ListDashboardsResponseBodyItem) UnsetV4() {
	o.V4.Unset()
}

// GetV5 returns the V5 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListDashboardsResponseBodyItem) GetV5() V5Dashboard {
	if o == nil || IsNil(o.V5.Get()) {
		var ret V5Dashboard
		return ret
	}
	return *o.V5.Get()
}

// GetV5Ok returns a tuple with the V5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListDashboardsResponseBodyItem) GetV5Ok() (*V5Dashboard, bool) {
	if o == nil {
		return nil, false
	}
	return o.V5.Get(), o.V5.IsSet()
}

// HasV5 returns a boolean if a field has been set.
func (o *ListDashboardsResponseBodyItem) HasV5() bool {
	if o != nil && o.V5.IsSet() {
		return true
	}

	return false
}

// SetV5 gets a reference to the given NullableV5Dashboard and assigns it to the V5 field.
func (o *ListDashboardsResponseBodyItem) SetV5(v V5Dashboard) {
	o.V5.Set(&v)
}
// SetV5Nil sets the value for V5 to be an explicit nil
func (o *ListDashboardsResponseBodyItem) SetV5Nil() {
	o.V5.Set(nil)
}

// UnsetV5 ensures that no value is present for V5, not even an explicit nil
func (o *ListDashboardsResponseBodyItem) UnsetV5() {
	o.V5.Unset()
}

// GetVersion returns the Version field value
func (o *ListDashboardsResponseBodyItem) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponseBodyItem) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ListDashboardsResponseBodyItem) SetVersion(v int32) {
	o.Version = v
}

func (o ListDashboardsResponseBodyItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDashboardsResponseBodyItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["dashboard_id"] = o.DashboardId
	toSerialize["description"] = o.Description
	toSerialize["folder_id"] = o.FolderId
	toSerialize["folder_name"] = o.FolderName
	toSerialize["hash"] = o.Hash
	toSerialize["owner"] = o.Owner
	toSerialize["role"] = o.Role
	toSerialize["title"] = o.Title
	toSerialize["updatedAt"] = o.UpdatedAt
	if o.V1.IsSet() {
		toSerialize["v1"] = o.V1.Get()
	}
	if o.V2.IsSet() {
		toSerialize["v2"] = o.V2.Get()
	}
	if o.V3.IsSet() {
		toSerialize["v3"] = o.V3.Get()
	}
	if o.V4.IsSet() {
		toSerialize["v4"] = o.V4.Get()
	}
	if o.V5.IsSet() {
		toSerialize["v5"] = o.V5.Get()
	}
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *ListDashboardsResponseBodyItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"dashboard_id",
		"description",
		"folder_id",
		"folder_name",
		"hash",
		"owner",
		"role",
		"title",
		"updatedAt",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDashboardsResponseBodyItem := _ListDashboardsResponseBodyItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDashboardsResponseBodyItem)

	if err != nil {
		return err
	}

	*o = ListDashboardsResponseBodyItem(varListDashboardsResponseBodyItem)

	return err
}

type NullableListDashboardsResponseBodyItem struct {
	value *ListDashboardsResponseBodyItem
	isSet bool
}

func (v NullableListDashboardsResponseBodyItem) Get() *ListDashboardsResponseBodyItem {
	return v.value
}

func (v *NullableListDashboardsResponseBodyItem) Set(val *ListDashboardsResponseBodyItem) {
	v.value = val
	v.isSet = true
}

func (v NullableListDashboardsResponseBodyItem) IsSet() bool {
	return v.isSet
}

func (v *NullableListDashboardsResponseBodyItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDashboardsResponseBodyItem(val *ListDashboardsResponseBodyItem) *NullableListDashboardsResponseBodyItem {
	return &NullableListDashboardsResponseBodyItem{value: val, isSet: true}
}

func (v NullableListDashboardsResponseBodyItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDashboardsResponseBodyItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


